# Generated by Django 5.0.6 on 2024-05-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_status_emotiondata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotiondata',
            old_name='happiness',
            new_name='joy',
        ),
    ]
